fix(ci): add remote branch fetching and error handling in sync-editorconfig job

diff --git a/.gitlab/ci/templates/coding-style/sync-coding-style.yml b/.gitlab/ci/templates/coding-style/sync-coding-style.yml
--- a/.gitlab/ci/templates/coding-style/sync-coding-style.yml
+++ b/.gitlab/ci/templates/coding-style/sync-coding-style.yml
@@ -72,6 +72,8 @@ sync-editorconfig:
       done
     - echo "Get all branches in the repository..."
     - git fetch --all
+    - git ls-remote --heads origin
+    - git ls-remote --heads origin || echo "🚨 git ls-remote failed"
     - REMOTE_BRANCHES=$(git ls-remote --heads origin | grep 'refs/heads/feature/' | sed 's#refs/heads/##')
     - |
       echo "🔄 Found remote branches: ${REMOTE_BRANCHES}"
